title: Kristina Joos
logo: "/images/round.png?raw=true"



<a href="https://www.linkedin.com/in/kristinajoos/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
