title: Kristina Joos # your name (or website title) here
logo: "/images/Joos_Kristina_AT (5 von 21).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   love solving complex problems with data!
   As a quality control professional in the pharmaceutical industry, digging into data, understanding complex systems, and breaking it down into valuable insights were at the core of my work.
   After I switched into the tech industry, I got excited about the endless possibilities of Data Science and decided to follow this passion. I am enthusiastic about learning, and currently, I am completing a data science immersive program at General Assembly.
   <br><br>
   Skills:
- Python
- Exploratory Data Analysis, Data Visualization
- Machine Learning Algorithms & Natural Language Processing
- Web Scraping | Relational Database Management |
- Git&Github
- Pharmaceuticals, Analytical Chemistry & Quality Control 
  <br><br>
  <a href="https://www.linkedin.com/in/kristinajoos/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
