title: Kristina Joos
logo: "/images/round.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I love solving complex problems with data
  <br><br>
  Skills
  Python<br>Exploratory Data Analysis<br>Data Visualization<br>Machine Learning Algorithms<br>Natural Language Processing<br>Web Scraping<br>Relational Database Management<br>Git&Github<br>Pharmaceuticals, Analytical Chemistry & Quality Control <br>

  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
