title: Kristina Joos
logo: "/images/round.png?raw=true"
description: > 
  I love solving complex problems with data.


  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
